language: go

go:
  - "1.10"

go_import_path: github.com/KuaishouContainerService/quota-order-webhook

# let us have speedy Docker-based Travis workers
sudo: false

script:
  - go build -o quota-order-webhook cmd/*.go
  - go vet ./...
  - go test ./...
