# deployment yaml
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: quota-order-webhook
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: quotaorder
        component: quota-order-webhook
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        operator: Exists
        key: node.cloudprovider.kubernetes.io/uninitialized
      nodeSelector:
         node-role.kubernetes.io/master: ""
      serviceAccount: quota-order-webhook
      containers:
        - name: quota-order-webhook
          image: kuaishou.com/lsj/quota-order-webhook:0.1.0
          env:
          - name: LOG_LEVEL
            value: debug
          - name: PORT
            value: "12345"

# service.yaml            
---
apiVersion: v1
kind: Service
metadata:
  name: quota-order-webhook
  namespace: kube-system
  labels:
    app: quotaorder
    component: quota-order-webhook
spec:
  type: NodePort
  ports:
  - port: 12345
    name: http
    targetPort: 12345
    nodePort: 32765
  selector:
    # select app=ingress-nginx pods
    app: quotaorder
    component: quota-order-webhook